# Generated by Django 3.2.10 on 2022-02-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('providerid', models.AutoField(db_column='providerID', primary_key=True, serialize=False)),
                ('providername', models.CharField(db_column='providerName', max_length=20, unique=True)),
                ('providerabbr', models.CharField(db_column='providerAbbr', max_length=2, unique=True)),
                ('isvalid', models.IntegerField(db_column='isValid', default=1)),
            ],
            options={
                'db_table': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagid', models.CharField(db_column='tagID', max_length=9, primary_key=True, serialize=False)),
                ('tagprovider', models.CharField(db_column='tagProvider', max_length=20)),
                ('isvalid', models.IntegerField(db_column='isValid', default=1)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.CharField(db_column='vehicleID', max_length=12, primary_key=True, serialize=False)),
                ('licenseyear', models.IntegerField(db_column='licenseYear')),
                ('isvalid', models.IntegerField(db_column='isValid', default=1)),
                ('providerabbr', models.ForeignKey(db_column='providerAbbr', on_delete=django.db.models.deletion.CASCADE, to='backend.provider')),
                ('tag', models.ForeignKey(db_column='tag', on_delete=django.db.models.deletion.CASCADE, to='backend.tag')),
            ],
            options={
                'db_table': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.CharField(db_column='stationID', max_length=10, primary_key=True, serialize=False)),
                ('stationname', models.CharField(db_column='stationName', max_length=30, unique=True)),
                ('isvalid', models.IntegerField(db_column='isValid', default=1)),
                ('stationprovider', models.ForeignKey(db_column='stationProvider', on_delete=django.db.models.deletion.CASCADE, to='backend.provider')),
            ],
            options={
                'db_table': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('passid', models.CharField(db_column='passID', max_length=10, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('charge', models.FloatField()),
                ('ishome', models.IntegerField(db_column='isHome')),
                ('stationref', models.ForeignKey(db_column='stationRef', on_delete=django.db.models.deletion.CASCADE, to='backend.station')),
                ('vehicleref', models.ForeignKey(db_column='vehicleRef', on_delete=django.db.models.deletion.CASCADE, to='backend.vehicle')),
            ],
            options={
                'db_table': 'Passes',
            },
        ),
    ]
