# Generated by Django 3.2.10 on 2021-12-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('providerid', models.AutoField(db_column='providerID', primary_key=True, serialize=False)),
                ('providername', models.CharField(db_column='providerName', max_length=20, unique=True)),
                ('providerabbr', models.CharField(db_column='providerAbbr', max_length=2, unique=True)),
                ('isvalid', models.IntegerField(db_column='isValid')),
            ],
            options={
                'db_table': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.CharField(db_column='vehicleID', max_length=12, primary_key=True, serialize=False)),
                ('tagid', models.CharField(db_column='tagID', max_length=9)),
                ('tagprovider', models.CharField(db_column='tagProvider', max_length=20)),
                ('licenseyear', models.IntegerField(db_column='licenseYear')),
                ('isvalid', models.IntegerField(db_column='isValid')),
                ('providerabbr', models.ForeignKey(db_column='providerAbbr', on_delete=django.db.models.deletion.CASCADE, to='backend.provider')),
            ],
            options={
                'db_table': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.CharField(db_column='stationID', max_length=10, primary_key=True, serialize=False)),
                ('stationname', models.CharField(db_column='stationName', max_length=30, unique=True)),
                ('isvalid', models.IntegerField(db_column='isValid')),
                ('stationprovider', models.ForeignKey(db_column='stationProvider', on_delete=django.db.models.deletion.CASCADE, to='backend.provider')),
            ],
            options={
                'db_table': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transactionid', models.AutoField(db_column='transactionID', primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('providercreditedid', models.ForeignKey(db_column='providerCreditedID', on_delete=django.db.models.deletion.CASCADE, related_name='provider_credited_id', to='backend.provider')),
                ('providerdebitedid', models.ForeignKey(db_column='providerDebitedID', on_delete=django.db.models.deletion.CASCADE, related_name='provider_debited_id', to='backend.provider')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('passid', models.CharField(db_column='passID', max_length=10, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('charge', models.FloatField()),
                ('ishome', models.IntegerField(db_column='isHome')),
                ('providerabbr', models.ForeignKey(db_column='providerAbbr', on_delete=django.db.models.deletion.CASCADE, to='backend.provider')),
                ('stationref', models.ForeignKey(db_column='stationRef', on_delete=django.db.models.deletion.CASCADE, to='backend.station')),
                ('vehicleref', models.ForeignKey(db_column='vehicleRef', on_delete=django.db.models.deletion.CASCADE, to='backend.vehicle')),
            ],
            options={
                'db_table': 'Passes',
            },
        ),
    ]
